# Generated by Django 4.2.6 on 2023-10-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('text_uz', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text_ru', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text_en', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='BarabanDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('name_ru', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('name_en', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Baraban_Discount',
            },
        ),
        migrations.CreateModel(
            name='BestSellerProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, default='nomi kiritilmagan', max_length=300, null=True)),
                ('name_ru', models.CharField(blank=True, default='nomi kiritilmagan', max_length=300, null=True)),
                ('name_en', models.CharField(blank=True, default='nomi kiritilmagan', max_length=300, null=True)),
                ('description_uz', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('description_ru', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('description_en', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='best_seller_images/')),
                ('best_seller_product', models.BooleanField(default=False)),
                ('text_color', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Бестселлер',
                'verbose_name_plural': 'Бестселлеры',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('phone_number', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('location', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('discount_name', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('total_cost', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Form',
            },
        ),
        migrations.CreateModel(
            name='Gallery_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='matn kiritilmagan', max_length=512)),
                ('title_ru', models.CharField(default='matn kiritilmagan', max_length=512)),
                ('title_en', models.CharField(default='matn kiritilmagan', max_length=512)),
                ('text_uz', models.TextField(default='matn kiritilmagan')),
                ('text_ru', models.TextField(default='matn kiritilmagan')),
                ('text_en', models.TextField(default='matn kiritilmagan')),
                ('img', models.ImageField(upload_to='images/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery_News',
                'verbose_name_plural': 'Gallery_News',
            },
        ),
        migrations.CreateModel(
            name='GalleryOnlyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Gallery_Only_Images',
            },
        ),
        migrations.CreateModel(
            name='Header_Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi_uz', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('nomi_en', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('nomi_ru', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('text_uz', models.TextField(blank=True, default='none', null=True)),
                ('text_ru', models.TextField(blank=True, default='none', null=True)),
                ('text_en', models.TextField(blank=True, default='none', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'header_carusel',
            },
        ),
        migrations.CreateModel(
            name='InfoGrafika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_product', models.CharField(default='40', max_length=30)),
                ('partners', models.CharField(default='10', max_length=30)),
                ('nominal_products', models.CharField(default='40', max_length=30)),
                ('nominal_products_last', models.CharField(default='40', max_length=30)),
                ('text', models.TextField(default='matn kiritilmagan')),
            ],
            options={
                'verbose_name_plural': 'Infografika',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('title_en', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('title_ru', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('text_uz', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text_ru', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text_en', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='ModelObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.TextField()),
                ('name_ru', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('phone_number', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('location', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('total_cost', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование товара ru')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tovar nomi uz')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name en')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код товара')),
                ('unit', models.CharField(choices=[('м2', 'м2'), ('шт', 'шт')], default='шт', max_length=10, verbose_name='Единица измерения')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Торговая марка')),
                ('proportions', models.CharField(blank=True, max_length=30, null=True, verbose_name='Размеры')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание ru')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif uz')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description en')),
                ('manufacturer', models.CharField(blank=True, max_length=20, null=True, verbose_name='Производитель')),
                ('rest_count', models.FloatField(default=0, verbose_name='Остаток товара')),
                ('is_float', models.BooleanField(default=False, verbose_name='Остаток является нецелым')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален ли товар')),
                ('top_product', models.BooleanField(default=False, verbose_name='Топ товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название категории ru')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya nomi uz')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product category en')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='ProductUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('facebook_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('telegram_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('youtube_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('whatsapp_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('linkedin_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('twitter_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('tiktok_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('pinterest_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social_Networks',
            },
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование товара ru')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tovar nomi uz')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name en')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код товара')),
                ('unit', models.CharField(choices=[('м2', 'м2'), ('шт', 'шт')], default='шт', max_length=10, verbose_name='Единица измерения')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Торговая марка')),
                ('proportions', models.CharField(max_length=30, verbose_name='Размеры')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание ru')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif uz')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description en')),
                ('manufacturer', models.CharField(blank=True, max_length=20, null=True, verbose_name='Производитель')),
                ('rest_count', models.FloatField(default=0, verbose_name='Остаток товара')),
                ('is_float', models.BooleanField(default=False, verbose_name='Остаток является нецелым')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален ли товар')),
            ],
            options={
                'verbose_name': 'Топ Товар',
                'verbose_name_plural': 'Топ Товары',
            },
        ),
        migrations.CreateModel(
            name='TopProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название категории ru')),
                ('name_uz', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya nomi uz')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product category en')),
            ],
            options={
                'verbose_name': 'Топ Бренд',
                'verbose_name_plural': 'Топ Бренды',
            },
        ),
        migrations.CreateModel(
            name='UsedProductsInWorksKale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.product')),
            ],
            options={
                'verbose_name_plural': 'Использованные товары в комнате',
            },
        ),
        migrations.CreateModel(
            name='WorksByKaleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('title_en', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('title_ru', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text_uz', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text_en', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text_ru', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
            ],
            options={
                'verbose_name': 'Работа в галерее kale',
                'verbose_name_plural': 'Работы Кале галереи',
            },
        ),
        migrations.CreateModel(
            name='WorksByKaleGalleryShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение для галереи')),
                ('works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.worksbykalegallery')),
            ],
            options={
                'verbose_name': 'Изображение для галереи',
                'verbose_name_plural': 'Изображение для галереи',
            },
        ),
        migrations.CreateModel(
            name='WorksByKale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('title_ru', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('title_en', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('text_uz', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text_ru', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text_en', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tour_link', models.URLField(blank=True, null=True)),
                ('long_desc_text_uz', models.TextField(blank=True, null=True)),
                ('long_desc_text_ru', models.TextField(blank=True, null=True)),
                ('long_desc_text_en', models.TextField(blank=True, null=True)),
                ('used_products', models.ManyToManyField(blank=True, to='basic_app.usedproductsinworkskale')),
            ],
            options={
                'verbose_name_plural': 'Works_By_Kale',
            },
        ),
        migrations.CreateModel(
            name='TopProductShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.topproduct')),
            ],
            options={
                'verbose_name': 'Топ Изображение товара',
                'verbose_name_plural': 'Топ Изображения товаров',
            },
        ),
        migrations.AddField(
            model_name='topproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic_app.topproductcategory'),
        ),
        migrations.CreateModel(
            name='ProductWorksByCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.worksbykale')),
            ],
            options={
                'verbose_name': 'Изображение сделанных работ',
                'verbose_name_plural': 'Изображение сделанных работ',
            },
        ),
        migrations.CreateModel(
            name='ProductShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.product')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic_app.productcategory'),
        ),
        migrations.CreateModel(
            name='MyObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.modelobjects')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.chatroom')),
            ],
        ),
    ]
